import { inter } from '@/app/fonts'
import '@/app/globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function ProductDetailLayout ({ children }) {
  return (
    <main className={`${inter.variable} font-product`}>{children}</main>
  )
}
